OskarLAspNet/Controllers/ProductCategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OskarLAspNet.Helpers.Services;
using OskarLAspNet.Models.ViewModels;

namespace OskarLAspNet.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private readonly ProductCategoryService _productCategoryService;

        public ProductCategoriesController(ProductCategoryService productCategoryService)
        {
            _productCategoryService = productCategoryService;
        }




        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CategoryRegVM viewModel)
        {
            //Kollar om category redan finns, finns det -> Felmeddelande. Annars Skapas category.
            if (ModelState.IsValid)
            {
                //1:34:00 ish f.10.
                var category = await _productCategoryService.GetCategoryAsync(viewModel.CategoryName);
                if (category != null)
                    //409
                    return Conflict(new { category, error = "This category already exists mylord." });

                category = await _productCategoryService.CreateProductCategoryAsync(viewModel);
                if (category != null)

                    //201
                    return Created("", category);
            }

            return View();
        }



        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

OskarLAspNet/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OskarLAspNet.Helpers.Services;
using OskarLAspNet.Models.Dtos;
using OskarLAspNet.Models.ViewModels;

namespace OskarLAspNet.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductService _productService;
        private readonly TagService _tagService;
        private readonly ProductCategoryService _productCategoryService;

        public ProductsController(ProductService productService, TagService tagService, ProductCategoryService productCategoryService)
        {
            _productService = productService;
            _tagService = tagService;
            _productCategoryService = productCategoryService;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllAsync();
            return View(products);
        }




        public async Task<IActionResult> Create()
        {
            ViewBag.Tags = await _tagService.GetTagsAsync();


            //TEST
            var categorySelectList = await _productCategoryService.GetCategorySelectListAsync();
            ViewBag.CategorySelectList = categorySelectList;


            return View();
        }



        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(ProductRegVM viewModel, string[] tags)
        {
            if (ModelState.IsValid)
            {

                var product = await _productService.CreateAsync(viewModel);
                if (product != null)
                {
                    if (viewModel.Image != null)
                        await _productService.UploadImageAsync(product, viewModel.Image);
                        await _productService.AddProductTagsAsync(viewModel, tags);
                 
                    return RedirectToAction("Index");
                }
                //TEST
                
                ModelState.AddModelError("", "Something Went Wrong.");
            }             
            
            ViewBag.Tags = await _tagService.GetTagsAsync(tags);
            
            return View(viewModel);
        }




        public async Task<IActionResult> ProductDetails(string articleNumber)
        {
            var product = await _productService.GetByArticleNumberAsync(articleNumber);

            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new ProductDetailViewModel
            {
                ArticleNumber = product.ArticleNumber,
                Name = product.ProductName,
                Price = product.Price,
                Description = product.ProductDescription,
                ImageUrl = product.ImageUrl
            };

            return View(viewModel);
        }

    }
}

OskarLAspNet/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OskarLAspNet.Helpers.Services;
using OskarLAspNet.Models.ViewModels;

namespace OskarLAspNet.Controllers
{
    public class TagsController : Controller
    {
        private readonly TagService _tagService;

        public TagsController(TagService tagService)
        {
            _tagService = tagService;
        }



        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(TagRegVM viewModel)
        {
            if (ModelState.IsValid)
            {
                //1:34:00 ish f.10.
                var tag = await _tagService.GetTagAsync(viewModel.TagName);
                if (tag != null)
                    //409
                    return Conflict(new { tag, error = "This tag already exists mylord." });

                tag = await _tagService.CreateTagAsync(viewModel);
                if (tag != null)

                    //201
                    return Created("", tag);
                RedirectToAction("/");
            }

            return View();
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Index(string? tag) //1:50:00 ish f.10
        {
            //Hämtar specifik
            if (!string.IsNullOrEmpty(tag))
            {
                var _tag = await _tagService.GetTagAsync(tag);
                if (_tag != null)
                    return Ok(_tag); //200
            }
            else
            {
                //Om inte sökkriterie är ifyllt, hämtar alla.
                var tags = await _tagService.GetAllTagsAsync();
                if (tags != null)
                    return Ok(tags); //200
            }

            return NotFound(new { tag, error = "This is not the tag you are looking for, are you sure it exists?" }); //404
        }
    }
}

OskarLAspNet/Views/Admin/AdminProducts.cshtml
@model IEnumerable<ProductEntity>
@{
    ViewData["Title"] = "Admin";
}


<div class="container">
    <h1 class="collection-title">All registered products</h1>

    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-md-4 mt-5">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">ArticleNumber: @product.ArticleNumber</h5>
                        <div>ProductName: @product.ProductName</div>
                        <div>Description: @product.ProductDescription</div>
                        <div>Price: @product.Price</div>
                        <div>Category: @product.ProductCategory</div>                      
                        
                        <div class="buttons">
                            <a class="link btn btn-danger" asp-controller="Admin" asp-action="Index">Delete Product</a>
                            <a class="link btn btn-success" asp-controller="Admin" asp-action="Index">Update Product</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    <a class="link btn btn-primary d-grid mb-5" asp-controller="Admin" asp-action="Index">Back to admin dashboard</a>
</div>

OskarLAspNet/Views/Admin/CreateUser.cshtml
@model UserRegisterVM

@{
    ViewData["Title"] = "Register a new account";
}


<section class="register-form">
    <div class="container">
        <div class="title">@ViewData["Title"]</div>

        <form method="post" enctype="multipart/form-data" novalidate>
            <div asp-validation-summary="ModelOnly" class="form-group error"></div>

            <div class="firstname form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="error"></span>
            </div>

            <div class="lastname form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" />
                <span asp-validation-for="LastName" class="error"></span>
            </div>

            <div class="streetname form-group">
                <label asp-for="StreetName"></label>
                <input asp-for="StreetName" />
                <span asp-validation-for="StreetName" class="error"></span>
            </div>

            <div class="postalcode form-group">
                <label asp-for="PostalCode"></label>
                <input asp-for="PostalCode" />
                <span asp-validation-for="PostalCode" class="error"></span>
            </div>

            <div class="city form-group">
                <label asp-for="City"></label>
                <input asp-for="City" />
                <span asp-validation-for="City" class="error"></span>
            </div>

            <div class="mobile form-group">
                <label asp-for="Mobile"></label>
                <input asp-for="Mobile" />
                <span asp-validation-for="Mobile" class="error"></span>
            </div>

            <div class="company form-group">
                <label asp-for="Company"></label>
                <input asp-for="Company" />
                <span asp-validation-for="Company" class="error"></span>
            </div>

            <div class="email form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" />
                <span asp-validation-for="Email" class="error"></span>
            </div>

            <div class="password form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" />
                <span asp-validation-for="Password" class="error"></span>

            </div><div class="confirmpassword form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" />
                <span asp-validation-for="ConfirmPassword" class="error"></span>
            </div>

            <div class="profileimage form-group">
                <label asp-for="ImageFile"></label>
                <input asp-for="ImageFile" />
                <span asp-validation-for="ImageFile" class="error"></span>
            </div>

            

            <button class="btn-theme">Submit</button>


        </form>



    </div>
</section>

OskarLAspNet/Views/Admin/GetAllUsers.cshtml
@model List<AppUser>
@inject UserManager<AppUser> UserManager

<div class="container">
    <div class="row">
        @foreach (var user in Model)
        {
            <div class="col-md-4 mt-5">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Firstname: @user.FirstName</h5>
                        <div>Lastname: @user.LastName</div>
                        <div>Companyname: @user.CompanyName</div>
                        <div>@user.ImageUrl</div>
                        <div>Email: @user.Email</div>

                        <h6>Roles:</h6>
                        <ul>
                            @if (User?.Identity?.IsAuthenticated == true)
                            {
                                var roles = await UserManager.GetRolesAsync(user);
                                foreach (var role in roles)
                                {
                                    <li>@role</li>
                                }
                            }
                        </ul>

                        <div class="buttons">
                            <a class="link btn btn-danger" asp-controller="Admin" asp-action="DeleteUser" asp-route-userId="@user.Id">Delete user</a>
                            <a class="link btn btn-success" asp-controller="Admin" asp-action="UpdateUser" asp-route-userId="@user.Id">Update user</a>
                            <form asp-controller="Admin" asp-action="ChangeUserRole" asp-route-userId="@user.Id" method="post" class="d-inline">
                                @Html.AntiForgeryToken()
                                <label for="newRole">Change Role:</label>
                                <select name="newRole">
                                    <option value="admin">Admin</option>
                                    <option value="user">User</option>
                                </select>
                                <button type="submit">Change</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <a class="link btn btn-primary d-grid mt-5" asp-controller="Admin" asp-action="Index">Back to admin dashboard</a>
</div>

OskarLAspNet/Views/Admin/Index.cshtml
<div class="container">
    <h3 class="d-flex justify-content-evenly mt-5 mb-5">Welcome @User.Identity.Name! This is your admin dashboard.</h3>  

    <div class="buttons d-flex justify-content-evenly mt-5 mb-5">
         
        <div class="dropdown">
            <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Show Stuff!
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" asp-controller="Admin" asp-action="GetAllUsers">Show all registered users</a></li>
                <li><a class="dropdown-item" asp-controller="Admin" asp-action="AdminProducts">Show all registered products</a></li>
                <li><a class="dropdown-item" asp-controller="Admin" asp-action="ShowAllComments">Show all registered comments from Contacts</a></li>

            </ul>
        </div>


        <div class="dropdown">
            <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Create Stuff!
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" asp-controller="Products" asp-action="Create"><i class="fa fa-plus"></i> Create new Product</a></li>
                <li><a class="dropdown-item" asp-controller="ProductCategories" asp-action="Create"><i class="fa fa-plus"></i> Create new Category</a></li>
                <li><a class="dropdown-item" asp-controller="Tags" asp-action="Create"><i class="fa fa-plus"></i> Create new Tag</a></li>
                <li><a class="dropdown-item" asp-controller="Admin" asp-action="CreateUser"><i class="fa fa-plus"></i> Create new User</a></li>
            </ul>
        </div>
    </div>
</div>

OskarLAspNet/Views/Admin/ShowAllComments.cshtml
@model IEnumerable<ContactFormEntryEntity>


<div class="container">
@foreach (var comment in Model)
{

    <div class="card bg-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Comment Registered: @comment.DateTime</div>
        <div class="card-body">
                <h5 class="card-title">@comment.Name</h5>
                <p class="card-text">@comment.Comment</p>
                <h5 class="card-title">Email: @comment.Email</h5>
                <h5 class="card-title">Mobile: @comment.PhoneNumber</h5>
                <h5 class="card-title">Company: @comment.Company</h5>
                <div class="buttons">
                    <a class="link btn btn-danger" asp-controller="Admin" asp-action="Index">Delete Comment</a>
                    
                </div>
        </div>
        
    </div>


}
    <a class="link btn btn-primary d-grid mb-5" asp-controller="Admin" asp-action="Index">Back to admin dashboard</a>
</div>